"""Add director column to Movie

Revision ID: 923823b18da6
Revises: 94cbf0d81070
Create Date: 2025-06-03 18:43:51.472794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923823b18da6'
down_revision = '94cbf0d81070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('director')

    # ### end Alembic commands ###
